### PR TITLE
add improved logic for handling vaulted files

### PR DESCRIPTION
**Pull request by scoopex**
Adapter configuration in https://github.com/osism/osism.github.io/pull/642/

### CODE REVIEW

**Comment by scoopex** [comment]
ready for review

**Comment by berendt** [comment]
@scoopex Resolve conflicts in Makefile first.

**Comment by scoopex** [comment]
> @scoopex Resolve conflicts in Makefile first.

I will check that tomorrow.

> @scoopex Resolve conflicts in Makefile first.

Done

**Comment by scoopex** [comment]
Added also some improvements, you can recheck  now.,

**Pull request merged**
